//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtensionSamples.Server.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnitExtension
    {
        public int ID_DB { get; set; }
        public int BusinessUnitId { get; set; }
        public string StationType { get; set; }
        public string StationFormat { get; set; }
        public string CustomerId { get; set; }
        public string RecipientId { get; set; }
        public string ChannelId { get; set; }
        public string CashBookId { get; set; }
        public string ProfitCenterId { get; set; }
        public string CostCenterId { get; set; }
    }
}
