//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtensionSamples.Server.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Storix.Common.DataAccess.EntityFramework;
    
    public partial class Storix_PortalEntities : DbContext
    {
        public int OrganizationId { get; set; }
    
        public Storix_PortalEntities()
            : base("name=Storix_PortalEntities")
        {
            BusinessUnitExtensions = new FilteredDbSet<BusinessUnitExtension>(base.Set<BusinessUnitExtension>(), e => e.ID_DB == OrganizationId);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        [Obsolete("Use Context.{DbSetObject(s)} Instead of Context.Set<{DbSetObject}>", true)]
        public new DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
                throw new Exception();
        }
    
        public virtual FilteredDbSet<BusinessUnitExtension> BusinessUnitExtensions { get; set; }
    }
}
